name: Deploy para Lightsail - AWS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Realizando checkout dos arquivos
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/bitnami/htdocs"
          EXCLUDE: "/dist/, /node_modules/"
