name: Implantação na AWS - Lightsail

on:
    push:
        branches:
            - main
    
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Realizando conferencia dos arquivos
      uses: actions/checkout@v4

    - name: Conectando no servidor e enviando arquivos
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/home/bitnami/htdocs"
